# Generated by Django 3.2.7 on 2021-10-15 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20211015_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='timetamp',
            new_name='timestamp',
        ),
    ]
